### ISSUE TITLE
Contributing updates for CentOS/RHEL, multiple versions, custom install path

### ISSUE THREAD

**Issue by brkane** [puppet-by-examples/puppet-ruby#8]
Hello!
I was happy to find your module on the Puppet Forge this week and used it for a basis for installing Ruby 1.9.3 from source on CentOS. If you're willing I'd love to contribute my updates back to your repo. Please let me know if you'd be interested.

Thanks again!

**Comment by gajdaw** [comment]
@brkane Hi Brian. Yes, I'd be gratefull if you could work on CentOS support.

**Comment by gajdaw** [comment]
@brkane I have just merged your changes. Thanks once again. Some changes were unavoidable.
